"use client";
import { EventType } from "@ag-ui/core";
import { FormEvent, useRef, useState } from "react";
import { buildAgentContext } from "@/lib/dayflow/agent/context";
import type { PlaceSummary, WeatherSummary } from "@/lib/dayflow/state/types";
import { useDayFlowStore } from "@/lib/dayflow/state/store";
type ChatMessage={id:string;role:"user"|"assistant";content:string}; type AgentEvent={type:string;[key:string]:unknown};
export function DayFlowChat({weather,visiblePlaces}:{weather:WeatherSummary|null;visiblePlaces:PlaceSummary[]}){const open=useDayFlowStore((s)=>s.runtime.chatOpen);const status=useDayFlowStore((s)=>s.runtime.agentStatus);const setOpen=useDayFlowStore((s)=>s.setChatOpen);const setStatus=useDayFlowStore((s)=>s.setAgentStatus);const applySnapshot=useDayFlowStore((s)=>s.applyAgentSnapshot);const applyDelta=useDayFlowStore((s)=>s.applyAgentDelta);const [input,setInput]=useState("");const [messages,setMessages]=useState<ChatMessage[]>([]);const threadId=useRef(crypto.randomUUID());
function handle(event:AgentEvent){switch(event.type){case EventType.STATE_SNAPSHOT:applySnapshot(event.snapshot);break;case EventType.STATE_DELTA:applyDelta(event.delta as never);break;case EventType.TEXT_MESSAGE_START:setMessages((m)=>[...m,{id:String(event.messageId),role:"assistant",content:""}]);break;case EventType.TEXT_MESSAGE_CONTENT:setMessages((m)=>m.map((x)=>x.id===event.messageId?{...x,content:x.content+String(event.delta??"")}:x));break;case EventType.RUN_ERROR:setStatus("error");setMessages((m)=>[...m,{id:crypto.randomUUID(),role:"assistant",content:String(event.message??"Agent error")}]);break;}}
async function submit(e:FormEvent){e.preventDefault();const prompt=input.trim();if(!prompt||status==="running")return;setInput("");setStatus("running");setMessages((m)=>[...m,{id:crypto.randomUUID(),role:"user",content:prompt}]);try{const state=useDayFlowStore.getState().shared;const context=buildAgentContext(state,weather,visiblePlaces);const response=await fetch("/api/dayflow-agent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt,threadId:threadId.current,state,context})});if(!response.ok||!response.body)throw new Error("Agent request failed");const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split("\n\n");buffer=chunks.pop()??"";for(const chunk of chunks){if(chunk.startsWith("data: "))handle(JSON.parse(chunk.slice(6)) as AgentEvent);}}setStatus("idle");}catch(error){setStatus("error");setMessages((m)=>[...m,{id:crypto.randomUUID(),role:"assistant",content:error instanceof Error?error.message:"Something went wrong."}]);}}
if(!open)return <button className="dayflow-chat-trigger" onClick={()=>setOpen(true)}>✦ Ask DayFlow</button>;return <aside className="dayflow-chat"><header><div><strong>✦ DayFlow</strong><small>City Copilot</small></div><button onClick={()=>setOpen(false)} aria-label="Close">×</button></header><section className="dayflow-chat-messages">{messages.length===0&&<div className="dayflow-chat-intro"><strong>What would you like to do?</strong><span>Try “Show cafés within 1 km.”</span></div>}{messages.map((m)=><div key={m.id} className={`dayflow-chat-message ${m.role}`}>{m.content}</div>)}{status==="running"&&<div className="dayflow-chat-loading">Working…</div>}</section><form className="dayflow-chat-composer" onSubmit={submit}><input value={input} onChange={(e)=>setInput(e.target.value)} placeholder="Ask DayFlow..."/><button type="submit" disabled={status==="running"}>↑</button></form></aside>}
